AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for creating a the network for the infrastructure'

Parameters:
  EnvironmentName:
    Type: String
    Description: 'The name of the environment. This will be used as a prefix for all resources created by this template.'
    AllowedPattern: '^[a-zA-Z0-9]+$'
    ConstraintDescription: 'Environment name must be alphanumeric and cannot contain spaces.'
  
  VpcCIDR:
    Type: String
    Description: 'The CIDR block for the VPC.'
    Default: '10.0.0.0/16'








Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Sub '${EnvironmentName}-vpc'









Output:
  VPCId:
    Description: 'The ID of the VPC.'
    Value: !Ref VPC
    Export:
      Name: !Sub '${EnvironmentName}-VPCId'