AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for creating a the network for the infrastructure'

Parameters:
  EnvironmentName:
    Type: String
    Description: 'The name of the environment. This will be used as a prefix for all resources created by this template.'
    AllowedPattern: '^[a-zA-Z0-9]+$'
    ConstraintDescription: 'Environment name must be alphanumeric and cannot contain spaces.'
  
  







Resources:









Output: